[package]
name = "xdg-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215", features = ["derive"] }
serde_yaml = "0.9.34"
toml = "0.8.19"
xdg = "2.5.2"
lib = { path = "../lib" }
dirs = "5.0.1"
